/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Device-tree lookups for LinuxKPI drivers (nextbsd-kernel#176).
 *
 * Linux drivers written against the platform bus find their own tree entry
 * through dev->of_node and walk it with of_parse_phandle() and friends. This
 * maps that handful of calls onto FreeBSD's OFW interface.
 *
 * Everything here is FDT-only. On a kernel without FDT the lookups return
 * NULL, which is what a Linux driver sees on a machine with no device tree,
 * so a caller that checks its return value behaves correctly rather than
 * needing to know which platform it is on.
 */

/*
 * opt_platform.h is generated by the kernel build; a module build may not have
 * it on the include path. FDT is what the guards below actually care about,
 * and every platform this driver can attach on is a device-tree platform.
 */
#if defined(__has_include)
#if __has_include("opt_platform.h")
#include "opt_platform.h"
#endif
#endif
#if !defined(FDT) && (defined(__aarch64__) || defined(__arm__))
#define	FDT
#endif

#include <sys/param.h>
#include <sys/systm.h>
#include <sys/malloc.h>
#include <sys/queue.h>
#include <sys/mutex.h>
#include <sys/lock.h>
#include <sys/bus.h>
#include <sys/rman.h>

#include <machine/bus.h>
#include <machine/resource.h>

#include <linux/device.h>
#include <linux/of.h>
#include <linux/platform_device.h>
#include <linux/err.h>
#include <linux/errno.h>

#ifdef FDT
#include <dev/ofw/openfirm.h>
#include <dev/ofw/ofw_bus.h>
#include <dev/ofw/ofw_bus_subr.h>
#endif

/*
 * Compare a device's node against a NULL-terminated match table, the way
 * of_match_device() does: first entry whose compatible string the node
 * claims wins, and the driver reads its ->data for the variant it matched.
 */
const struct of_device_id *
of_match_device(const struct of_device_id *matches, const struct device *dev)
{
#ifdef FDT
	const struct of_device_id *m;

	if (matches == NULL || dev == NULL || dev->of_node == NULL)
		return (NULL);

	for (m = matches; m->compatible[0] != '\0'; m++) {
		if (ofw_bus_node_is_compatible((phandle_t)dev->of_node->node,
		    m->compatible))
			return (m);
	}
#endif
	return (NULL);
}

/*
 * Follow a phandle property to the node it names.
 *
 * The returned struct device_node is allocated here and released by
 * of_node_put(), which is the ownership Linux callers already expect -- they
 * put what they parse. FreeBSD's phandle_t is a plain value with no
 * refcounting behind it, so the allocation exists purely to give the caller
 * something with the shape it is written against.
 */
struct device_node *
of_parse_phandle(const struct device_node *np, const char *name, int index)
{
#ifdef FDT
	struct device_node *dn;
	phandle_t *handles;
	phandle_t target;
	ssize_t nhandles;

	if (np == NULL || name == NULL || index < 0)
		return (NULL);

	/* Returns the number of elements, not bytes. */
	nhandles = OF_getencprop_alloc_multi((phandle_t)np->node, name,
	    sizeof(phandle_t), (void **)&handles);
	if (nhandles <= 0)
		return (NULL);
	if (index >= nhandles) {
		OF_prop_free(handles);
		return (NULL);
	}
	target = OF_node_from_xref(handles[index]);
	OF_prop_free(handles);
	if (target == 0)
		return (NULL);

	dn = malloc(sizeof(*dn), M_DEVBUF, M_NOWAIT | M_ZERO);
	if (dn == NULL)
		return (NULL);
	dn->node = (intptr_t)target;
	return (dn);
#else
	return (NULL);
#endif
}

struct device_node *
of_node_get(struct device_node *np)
{

	return (np);
}

void
of_node_put(struct device_node *np)
{

	free(np, M_DEVBUF);
}

#ifdef FDT
/*
 * Next node in depth-first order: child, else next sibling, else walk back up
 * until a parent has one. Returns 0 at the end of the tree.
 *
 * Written out rather than reusing an ofw_bus_ helper because none of them
 * enumerate the whole tree -- they search one parent's children.
 */
static phandle_t
of_next_node(phandle_t node)
{
	phandle_t n;

	if (node == 0)
		return (OF_peer(0));		/* start: the root */
	if ((n = OF_child(node)) != 0)
		return (n);
	while (node != 0) {
		if ((n = OF_peer(node)) != 0)
			return (n);
		node = OF_parent(node);
	}
	return (0);
}
#endif

/*
 * Next node after `from` whose compatible list contains `compat` (#51).
 *
 * `from` is consumed exactly as Linux does -- the caller's reference is
 * dropped whether or not a match is found -- so
 *
 *	while ((np = of_find_compatible_node(np, NULL, "x")) != NULL)
 *
 * does not leak. `type` (device_type) is accepted for signature compatibility
 * and ignored: deprecated in modern bindings, and no vc4 caller passes it.
 */
struct device_node *
of_find_compatible_node(struct device_node *from, const char *type __unused,
    const char *compat)
{
#ifdef FDT
	struct device_node *np;
	phandle_t node;

	if (compat == NULL)
		return (NULL);
	node = (from != NULL) ? (phandle_t)from->node : 0;
	if (from != NULL)
		of_node_put(from);

	while ((node = of_next_node(node)) != 0) {
		if (!ofw_bus_node_is_compatible(node, compat))
			continue;
		np = malloc(sizeof(*np), M_DEVBUF, M_NOWAIT | M_ZERO);
		if (np == NULL)
			return (NULL);
		np->node = node;
		return (np);
	}
	return (NULL);
#else
	if (from != NULL)
		of_node_put(from);
	return (NULL);
#endif
}

/*
 * As above, but matching a table and reporting WHICH entry matched -- how a
 * driver picks per-variant data for the node it found.
 */
struct device_node *
of_find_matching_node_and_match(struct device_node *from,
    const struct of_device_id *matches, const struct of_device_id **match)
{
#ifdef FDT
	struct device_node *np;
	const struct of_device_id *id;
	phandle_t node;

	if (match != NULL)
		*match = NULL;
	if (matches == NULL)
		return (NULL);
	node = (from != NULL) ? (phandle_t)from->node : 0;
	if (from != NULL)
		of_node_put(from);

	while ((node = of_next_node(node)) != 0) {
		for (id = matches; id->compatible[0] != '\0'; id++) {
			if (!ofw_bus_node_is_compatible(node, id->compatible))
				continue;
			np = malloc(sizeof(*np), M_DEVBUF, M_NOWAIT | M_ZERO);
			if (np == NULL)
				return (NULL);
			np->node = node;
			if (match != NULL)
				*match = id;
			return (np);
		}
	}
	return (NULL);
#else
	if (from != NULL)
		of_node_put(from);
	return (NULL);
#endif
}

/*
 * ofw_bus_node_status_okay() implements Linux's rule: absent status means
 * available, "okay"/"ok" mean available, anything else does not.
 */
bool
of_device_is_available(const struct device_node *np)
{
#ifdef FDT
	if (np == NULL)
		return (false);
	return (ofw_bus_node_status_okay((phandle_t)np->node) != 0);
#else
	return (false);
#endif
}

bool
of_device_is_compatible(const struct device_node *np, const char *compat)
{
#ifdef FDT
	if (np == NULL || compat == NULL)
		return (false);
	return (ofw_bus_node_is_compatible((phandle_t)np->node, compat) != 0);
#else
	return (false);
#endif
}

/*
 * The per-variant data from the of_device_id entry that matched this device.
 * vc4 uses it to tell BCM2712 from earlier parts, so the wrong entry here
 * selects the wrong register layout.
 */
const void *
of_device_get_match_data(const struct device *dev)
{
#ifdef FDT
	const struct of_device_id *id;

	if (dev == NULL || dev->driver == NULL)
		return (NULL);
	id = of_match_device(dev->driver->of_match_table, dev);
	return (id != NULL ? id->data : NULL);
#else
	return (NULL);
#endif
}

/* See linux/of.h for why this does nothing and when that stops being true. */
int
of_dma_configure(struct device *dev __unused, struct device_node *np __unused,
    bool force_dma __unused)
{

	return (0);
}

/*
 * Body of devm_platform_ioremap_resource(); see the comment on its declaration
 * in <linux/platform_device.h> for why it cannot be inline there.
 *
 * "struct resource" in this file is FreeBSD's, from sys/rman.h -- this
 * translation unit deliberately does not include <linux/ioport.h>, which
 * declares an unrelated type of the same name.
 */
void *
lkpi_platform_ioremap_resource(struct platform_device *pdev, unsigned int index)
{
	struct resource *res;
	int rid = (int)index;

	if (pdev == NULL || pdev->dev.bsddev == NULL)
		return (ERR_PTR(-ENODEV));
	res = bus_alloc_resource_any(pdev->dev.bsddev, SYS_RES_MEMORY, &rid,
	    RF_ACTIVE | RF_SHAREABLE);
	if (res == NULL)
		return (ERR_PTR(-ENOMEM));
	/*
	 * NOT rman_get_bushandle(): that is a bus_space_handle_t, which on some
	 * architectures is not pointer-sized, so casting it to void * is wrong
	 * as well as unportable.
	 */
	return (rman_get_virtual(res));
}

/*
 * How many interrupts the node actually has, so an out-of-range index is
 * reported as -ENXIO here rather than as a resource allocation failure much
 * later. ofw_bus_intr_to_rl() has already turned the node's interrupts
 * property into a resource list on the newbus device, so counting IRQ entries
 * there matches exactly what bus_alloc_resource_any() will be able to hand out.
 */
static int
lkpi_of_irq_count(struct platform_device *pdev)
{
#ifdef FDT
	struct resource_list *rl;
	struct resource_list_entry *rle;
	int n;

	if (pdev->dev.bsddev == NULL)
		return (0);
	rl = BUS_GET_RESOURCE_LIST(device_get_parent(pdev->dev.bsddev),
	    pdev->dev.bsddev);
	if (rl == NULL)
		return (0);
	n = 0;
	STAILQ_FOREACH(rle, rl, link) {
		if (rle->type == SYS_RES_IRQ)
			n++;
	}
	return (n);
#else
	return (0);
#endif
}

int
lkpi_platform_get_irq(struct platform_device *pdev, unsigned int num)
{

	if (pdev == NULL)
		return (-ENXIO);

	/*
	 * A device with a single interrupt read at attach keeps working
	 * through dev->irq, untagged, which request_irq() treats as rid 0.
	 * This is the path firmware KMS takes.
	 */
	if (num == 0 && lkpi_of_irq_count(pdev) <= 1) {
		if (pdev->dev.irq == LINUX_IRQ_INVALID)
			return (-ENXIO);
		return ((int)pdev->dev.irq);
	}

	if ((int)num >= lkpi_of_irq_count(pdev))
		return (-ENXIO);
	return ((int)LKPI_IRQ_OF(num));
}

/*
 * Resolve a name against the node's interrupt-names property.
 *
 * interrupt-names is a list of NUL-separated strings, one per entry in
 * interrupts, in the same order -- so the index of the matching name is the
 * index of the interrupt, which is the rid.
 */
int
lkpi_platform_get_irq_byname(struct platform_device *pdev, const char *name)
{
#ifdef FDT
	char *names;
	phandle_t node;
	int i, len, off;

	if (pdev == NULL || name == NULL || pdev->dev.of_node == NULL)
		return (-ENXIO);
	node = (phandle_t)pdev->dev.of_node->node;
	if (node == 0)
		return (-ENXIO);

	len = OF_getprop_alloc(node, "interrupt-names", (void **)&names);
	if (len <= 0)
		return (-ENXIO);

	for (i = 0, off = 0; off < len; i++) {
		if (strcmp(&names[off], name) == 0) {
			OF_prop_free(names);
			if (i >= lkpi_of_irq_count(pdev))
				return (-ENXIO);
			return ((int)LKPI_IRQ_OF(i));
		}
		off += strlen(&names[off]) + 1;
	}
	OF_prop_free(names);
	return (-ENXIO);
#else
	return (-ENXIO);
#endif
}

/*
 * struct device -> device_node, replacing the dev->of_node field that kernel
 * patch 0040 used to add. See <linux/of.h> for why that field had to go.
 *
 * A vc4 pipeline is five devices, so a list is the right shape; entries are
 * added from attach and removed from detach, neither of which is hot.
 */
struct lkpi_of_ent {
	TAILQ_ENTRY(lkpi_of_ent)	 link;
	struct device			*dev;
	struct device_node		*node;
};

static TAILQ_HEAD(, lkpi_of_ent) lkpi_of_nodes =
    TAILQ_HEAD_INITIALIZER(lkpi_of_nodes);
static struct mtx lkpi_of_mtx;
MTX_SYSINIT(lkpi_of_mtx, &lkpi_of_mtx, "lkpi-of-nodes", MTX_DEF);

void
lkpi_set_of_node(struct device *dev, struct device_node *node)
{
	struct lkpi_of_ent *e;

	if (dev == NULL)
		return;
	e = malloc(sizeof(*e), M_DEVBUF, M_WAITOK | M_ZERO);
	e->dev = dev;
	e->node = node;
	mtx_lock(&lkpi_of_mtx);
	TAILQ_INSERT_TAIL(&lkpi_of_nodes, e, link);
	mtx_unlock(&lkpi_of_mtx);
}

void
lkpi_clear_of_node(struct device *dev)
{
	struct lkpi_of_ent *e, *tmp;

	mtx_lock(&lkpi_of_mtx);
	TAILQ_FOREACH_SAFE(e, &lkpi_of_nodes, link, tmp) {
		if (e->dev != dev)
			continue;
		TAILQ_REMOVE(&lkpi_of_nodes, e, link);
		mtx_unlock(&lkpi_of_mtx);
		free(e, M_DEVBUF);
		return;
	}
	mtx_unlock(&lkpi_of_mtx);
}

struct device_node *
dev_of_node(struct device *dev)
{
	struct lkpi_of_ent *e;
	struct device_node *n = NULL;

	if (dev == NULL)
		return (NULL);
	mtx_lock(&lkpi_of_mtx);
	TAILQ_FOREACH(e, &lkpi_of_nodes, link) {
		if (e->dev == dev) {
			n = e->node;
			break;
		}
	}
	mtx_unlock(&lkpi_of_mtx);
	return (n);
}
